apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    io.service: enqualify-mapi
  name: enqualify-mapi
  namespace: {{ .Values.namespace }}
spec:
  selector:
    io.service: enqualify-mapi
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
  - host: {{ .Values.rules.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enqualify-mapi
            port:
              number: 8080